//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 08:50:37 PM EST 
//


package com.ez_konnect.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Definition for Business's general information.
 *             
 * 
 * <p>Java class for AssociatedBusinessGeneralInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedBusinessGeneralInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BusinessGeneralInfo" type="{http://ez-konnect.com/v1}BusinessGeneralInfoType"/&gt;
 *         &lt;element name="MsgInfo" type="{http://ez-konnect.com/v1}MsgInfoType" minOccurs="0"/&gt;
 *         &lt;element name="MsgList" type="{http://ez-konnect.com/v1}MsgListType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedBusinessGeneralInfoType", propOrder = {
    "businessGeneralInfo",
    "msgInfo",
    "msgList"
})
public class AssociatedBusinessGeneralInfoType {

    @XmlElement(name = "BusinessGeneralInfo", required = true)
    protected BusinessGeneralInfoType businessGeneralInfo;
    @XmlElement(name = "MsgInfo")
    protected MsgInfoType msgInfo;
    @XmlElement(name = "MsgList", required = true)
    protected List<MsgListType> msgList;

    /**
     * Gets the value of the businessGeneralInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessGeneralInfoType }
     *     
     */
    public BusinessGeneralInfoType getBusinessGeneralInfo() {
        return businessGeneralInfo;
    }

    /**
     * Sets the value of the businessGeneralInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessGeneralInfoType }
     *     
     */
    public void setBusinessGeneralInfo(BusinessGeneralInfoType value) {
        this.businessGeneralInfo = value;
    }

    /**
     * Gets the value of the msgInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MsgInfoType }
     *     
     */
    public MsgInfoType getMsgInfo() {
        return msgInfo;
    }

    /**
     * Sets the value of the msgInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgInfoType }
     *     
     */
    public void setMsgInfo(MsgInfoType value) {
        this.msgInfo = value;
    }

    /**
     * Gets the value of the msgList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the msgList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMsgList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MsgListType }
     * 
     * 
     */
    public List<MsgListType> getMsgList() {
        if (msgList == null) {
            msgList = new ArrayList<MsgListType>();
        }
        return this.msgList;
    }

}
