//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 08:50:37 PM EST 
//


package com.ez_konnect.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Definition for a Business.
 *                     Consist of -
 *                         Business general information
 *                         Conatct information
 *                         Associated linkages
 *                         Associated accounts
 *                         Regions the Businesss can operate
 *                         The service subscription
 *             
 * 
 * <p>Java class for BusinessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BusinessGeneralInfo" type="{http://ez-konnect.com/v1}BusinessGeneralInfoType"/&gt;
 *         &lt;element name="BusinessContacts" type="{http://ez-konnect.com/v1}ContactListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessType", propOrder = {
    "businessGeneralInfo",
    "businessContacts"
})
public class BusinessType {

    @XmlElement(name = "BusinessGeneralInfo", required = true)
    protected BusinessGeneralInfoType businessGeneralInfo;
    @XmlElement(name = "BusinessContacts")
    protected ContactListType businessContacts;

    /**
     * Gets the value of the businessGeneralInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessGeneralInfoType }
     *     
     */
    public BusinessGeneralInfoType getBusinessGeneralInfo() {
        return businessGeneralInfo;
    }

    /**
     * Sets the value of the businessGeneralInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessGeneralInfoType }
     *     
     */
    public void setBusinessGeneralInfo(BusinessGeneralInfoType value) {
        this.businessGeneralInfo = value;
    }

    /**
     * Gets the value of the businessContacts property.
     * 
     * @return
     *     possible object is
     *     {@link ContactListType }
     *     
     */
    public ContactListType getBusinessContacts() {
        return businessContacts;
    }

    /**
     * Sets the value of the businessContacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactListType }
     *     
     */
    public void setBusinessContacts(ContactListType value) {
        this.businessContacts = value;
    }

}
