//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 08:50:37 PM EST 
//


package com.ez_konnect.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The response object for provisioning
 *             
 * 
 * <p>Java class for EntityResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ActionData" type="{http://ez-konnect.com/v1}ActionDataType" minOccurs="0"/&gt;
 *         &lt;element name="User" type="{http://ez-konnect.com/v1}UserType" minOccurs="0"/&gt;
 *         &lt;element name="SearchResult" type="{http://ez-konnect.com/v1}SearchResultType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityResponseType", propOrder = {
    "actionData",
    "user",
    "searchResult"
})
public class EntityResponseType {

    @XmlElement(name = "ActionData")
    protected ActionDataType actionData;
    @XmlElement(name = "User")
    protected UserType user;
    @XmlElement(name = "SearchResult")
    protected SearchResultType searchResult;

    /**
     * Gets the value of the actionData property.
     * 
     * @return
     *     possible object is
     *     {@link ActionDataType }
     *     
     */
    public ActionDataType getActionData() {
        return actionData;
    }

    /**
     * Sets the value of the actionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionDataType }
     *     
     */
    public void setActionData(ActionDataType value) {
        this.actionData = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUser(UserType value) {
        this.user = value;
    }

    /**
     * Gets the value of the searchResult property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResultType }
     *     
     */
    public SearchResultType getSearchResult() {
        return searchResult;
    }

    /**
     * Sets the value of the searchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResultType }
     *     
     */
    public void setSearchResult(SearchResultType value) {
        this.searchResult = value;
    }

}
