//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 08:50:37 PM EST 
//


package com.ez_konnect.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *              
 * 
 * <p>Java class for MsgInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MsgInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UnReadMsgs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReadMsgs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TotalMsgs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MsgInfoType", propOrder = {
    "unReadMsgs",
    "readMsgs",
    "totalMsgs"
})
public class MsgInfoType {

    @XmlElement(name = "UnReadMsgs")
    protected String unReadMsgs;
    @XmlElement(name = "ReadMsgs")
    protected String readMsgs;
    @XmlElement(name = "TotalMsgs")
    protected String totalMsgs;

    /**
     * Gets the value of the unReadMsgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnReadMsgs() {
        return unReadMsgs;
    }

    /**
     * Sets the value of the unReadMsgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnReadMsgs(String value) {
        this.unReadMsgs = value;
    }

    /**
     * Gets the value of the readMsgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadMsgs() {
        return readMsgs;
    }

    /**
     * Sets the value of the readMsgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadMsgs(String value) {
        this.readMsgs = value;
    }

    /**
     * Gets the value of the totalMsgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalMsgs() {
        return totalMsgs;
    }

    /**
     * Sets the value of the totalMsgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalMsgs(String value) {
        this.totalMsgs = value;
    }

}
