//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 08:50:37 PM EST 
//


package com.ez_konnect.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ez_konnect.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EntityResponse_QNAME = new QName("http://ez-konnect.com/v1", "EntityResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ez_konnect.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityResponseType }
     * 
     */
    public EntityResponseType createEntityResponseType() {
        return new EntityResponseType();
    }

    /**
     * Create an instance of {@link RequestGlobalIDType }
     * 
     */
    public RequestGlobalIDType createRequestGlobalIDType() {
        return new RequestGlobalIDType();
    }

    /**
     * Create an instance of {@link BusinessType }
     * 
     */
    public BusinessType createBusinessType() {
        return new BusinessType();
    }

    /**
     * Create an instance of {@link AssociatedBusinessGeneralInfoType }
     * 
     */
    public AssociatedBusinessGeneralInfoType createAssociatedBusinessGeneralInfoType() {
        return new AssociatedBusinessGeneralInfoType();
    }

    /**
     * Create an instance of {@link BusinessGeneralInfoType }
     * 
     */
    public BusinessGeneralInfoType createBusinessGeneralInfoType() {
        return new BusinessGeneralInfoType();
    }

    /**
     * Create an instance of {@link MsgListType }
     * 
     */
    public MsgListType createMsgListType() {
        return new MsgListType();
    }

    /**
     * Create an instance of {@link MsgInfoType }
     * 
     */
    public MsgInfoType createMsgInfoType() {
        return new MsgInfoType();
    }

    /**
     * Create an instance of {@link ContactListType }
     * 
     */
    public ContactListType createContactListType() {
        return new ContactListType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link RegionType }
     * 
     */
    public RegionType createRegionType() {
        return new RegionType();
    }

    /**
     * Create an instance of {@link CountryListType }
     * 
     */
    public CountryListType createCountryListType() {
        return new CountryListType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link SimpleValueListType }
     * 
     */
    public SimpleValueListType createSimpleValueListType() {
        return new SimpleValueListType();
    }

    /**
     * Create an instance of {@link SearchResultType }
     * 
     */
    public SearchResultType createSearchResultType() {
        return new SearchResultType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link UserGeneralInfoType }
     * 
     */
    public UserGeneralInfoType createUserGeneralInfoType() {
        return new UserGeneralInfoType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link EntityRequestType }
     * 
     */
    public EntityRequestType createEntityRequestType() {
        return new EntityRequestType();
    }

    /**
     * Create an instance of {@link ActionDataType }
     * 
     */
    public ActionDataType createActionDataType() {
        return new ActionDataType();
    }

    /**
     * Create an instance of {@link ErrorListType }
     * 
     */
    public ErrorListType createErrorListType() {
        return new ErrorListType();
    }

    /**
     * Create an instance of {@link OpValueType }
     * 
     */
    public OpValueType createOpValueType() {
        return new OpValueType();
    }

    /**
     * Create an instance of {@link UserActionType }
     * 
     */
    public UserActionType createUserActionType() {
        return new UserActionType();
    }

    /**
     * Create an instance of {@link SecurityContactType }
     * 
     */
    public SecurityContactType createSecurityContactType() {
        return new SecurityContactType();
    }

    /**
     * Create an instance of {@link WeekDaysListType }
     * 
     */
    public WeekDaysListType createWeekDaysListType() {
        return new WeekDaysListType();
    }

    /**
     * Create an instance of {@link AssociatedBusinessesListType }
     * 
     */
    public AssociatedBusinessesListType createAssociatedBusinessesListType() {
        return new AssociatedBusinessesListType();
    }

    /**
     * Create an instance of {@link BusinessesListType }
     * 
     */
    public BusinessesListType createBusinessesListType() {
        return new BusinessesListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ez-konnect.com/v1", name = "EntityResponse")
    public JAXBElement<EntityResponseType> createEntityResponse(EntityResponseType value) {
        return new JAXBElement<EntityResponseType>(_EntityResponse_QNAME, EntityResponseType.class, null, value);
    }

}
