//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 08:50:37 PM EST 
//


package com.ez_konnect.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreferredContactMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PreferredContactMethodType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="WorkNumber"/&gt;
 *     &lt;enumeration value="HomeNumber"/&gt;
 *     &lt;enumeration value="CellNumber"/&gt;
 *     &lt;enumeration value="FaxNumber"/&gt;
 *     &lt;enumeration value="Email"/&gt;
 *     &lt;enumeration value="Telex"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PreferredContactMethodType")
@XmlEnum
public enum PreferredContactMethodType {

    @XmlEnumValue("WorkNumber")
    WORK_NUMBER("WorkNumber"),
    @XmlEnumValue("HomeNumber")
    HOME_NUMBER("HomeNumber"),
    @XmlEnumValue("CellNumber")
    CELL_NUMBER("CellNumber"),
    @XmlEnumValue("FaxNumber")
    FAX_NUMBER("FaxNumber"),
    @XmlEnumValue("Email")
    EMAIL("Email"),
    @XmlEnumValue("Telex")
    TELEX("Telex");
    private final String value;

    PreferredContactMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PreferredContactMethodType fromValue(String v) {
        for (PreferredContactMethodType c: PreferredContactMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
