//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 08:50:37 PM EST 
//


package com.ez_konnect.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 User Definition.
 *             
 * 
 * <p>Java class for SearchResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SearchedCriteria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SearchedBusinesses" type="{http://ez-konnect.com/v1}BusinessesListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchResultType", propOrder = {
    "searchedCriteria",
    "searchedBusinesses"
})
public class SearchResultType {

    @XmlElement(name = "SearchedCriteria")
    protected String searchedCriteria;
    @XmlElement(name = "SearchedBusinesses")
    protected BusinessesListType searchedBusinesses;

    /**
     * Gets the value of the searchedCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchedCriteria() {
        return searchedCriteria;
    }

    /**
     * Sets the value of the searchedCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchedCriteria(String value) {
        this.searchedCriteria = value;
    }

    /**
     * Gets the value of the searchedBusinesses property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessesListType }
     *     
     */
    public BusinessesListType getSearchedBusinesses() {
        return searchedBusinesses;
    }

    /**
     * Sets the value of the searchedBusinesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessesListType }
     *     
     */
    public void setSearchedBusinesses(BusinessesListType value) {
        this.searchedBusinesses = value;
    }

}
