//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.26 at 08:50:37 PM EST 
//


package com.ez_konnect.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 User Definition.
 *             
 * 
 * <p>Java class for UserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UserGeneralInfo" type="{http://ez-konnect.com/v1}UserGeneralInfoType"/&gt;
 *         &lt;element name="AssociatedBusinessSubscriptions" type="{http://ez-konnect.com/v1}AssociatedBusinessesListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserType", propOrder = {
    "userGeneralInfo",
    "associatedBusinessSubscriptions"
})
public class UserType {

    @XmlElement(name = "UserGeneralInfo", required = true)
    protected UserGeneralInfoType userGeneralInfo;
    @XmlElement(name = "AssociatedBusinessSubscriptions")
    protected AssociatedBusinessesListType associatedBusinessSubscriptions;

    /**
     * Gets the value of the userGeneralInfo property.
     * 
     * @return
     *     possible object is
     *     {@link UserGeneralInfoType }
     *     
     */
    public UserGeneralInfoType getUserGeneralInfo() {
        return userGeneralInfo;
    }

    /**
     * Sets the value of the userGeneralInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserGeneralInfoType }
     *     
     */
    public void setUserGeneralInfo(UserGeneralInfoType value) {
        this.userGeneralInfo = value;
    }

    /**
     * Gets the value of the associatedBusinessSubscriptions property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedBusinessesListType }
     *     
     */
    public AssociatedBusinessesListType getAssociatedBusinessSubscriptions() {
        return associatedBusinessSubscriptions;
    }

    /**
     * Sets the value of the associatedBusinessSubscriptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedBusinessesListType }
     *     
     */
    public void setAssociatedBusinessSubscriptions(AssociatedBusinessesListType value) {
        this.associatedBusinessSubscriptions = value;
    }

}
